version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.5
    - 8.2.7
    - 8.2.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: snowpack
    versions:
    - 3.0.11
    - 3.0.12
    - 3.0.13
    - 3.1.2
    - 3.2.2
    - 3.3.0
    - 3.3.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: cssnano
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: stylelint-prettier
    versions:
    - 1.2.0
  - dependency-name: stylelint-config-recommended
    versions:
    - 4.0.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
    - 12.1.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: pug
    versions:
    - 3.0.1
  - dependency-name: postcss-nested
    versions:
    - 5.0.4
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: stylelint
    versions:
    - 13.11.0
